package com.sunwayworld.cloud.module.lcdp.base.sourcecode;

import java.util.Arrays;
import java.util.List;

public enum LcdpSourceCodeMethodType {
    COMPONNET_TABLE(Arrays.asList("java.lang.String")),
    GRID_SETID(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map")),
    GRID_INSERT(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map")),
    GRID_UPDATE(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map",
            "com.sunwayworld.framework.utils.StringUtils",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpResultDTO")),
    GRID_DELETE(Arrays.asList("java.lang.String",
            "java.util.List",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpResultDTO")),
    GRID_LIST(Arrays.asList("java.lang.String",
            "java.util.Map",
            "com.sunwayworld.framework.mybatis.mapper.MapperParameter")),
    GRID_PAGINATION(Arrays.asList("java.lang.String",
            "java.util.Map",
            "com.sunwayworld.framework.data.page.Page",
            "com.sunwayworld.framework.mybatis.mapper.MapperParameter",
            "com.sunwayworld.framework.mybatis.page.PageRowBounds")),
    GRID_ACTIVATE(Arrays.asList("java.time.LocalDateTime",
            "java.util.Map",
            "com.sunwayworld.framework.constant.Constant",
            "com.sunwayworld.framework.utils.ArrayUtils",
            "com.sunwayworld.framework.context.LocalContextHelper")),
    GRID_DEACTIVATE(Arrays.asList("java.time.LocalDateTime",
            "java.util.Map",
            "com.sunwayworld.framework.constant.Constant",
            "com.sunwayworld.framework.utils.ArrayUtils",
            "com.sunwayworld.framework.context.LocalContextHelper")),
    GRID_SWAP(Arrays.asList("java.lang.String",
            "java.util.Map",
            "com.sunwayworld.framework.database.context.TableContext",
            "com.sunwayworld.framework.utils.ArrayUtils",
            "com.sunwayworld.framework.utils.NumberUtils",
            "com.sunwayworld.framework.utils.CollectionUtils",
            "com.sunwayworld.framework.utils.StringUtils")),
    GRID_PROCESSTASKSTATUS(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpAuditableDTO",
            "com.sunwayworld.framework.support.auditable.bean.CoreBpmnParameterDTO")),
    GRID_STARTPROCESS(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpAuditableDTO",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpResultDTO",
            "com.sunwayworld.framework.context.concurrent.GikamConcurrentLocker",
            "com.sunwayworld.framework.support.auditable.bean.CoreBpmnParameterDTO",
            "com.sunwayworld.module.sys.bpmn.CoreBpmnHelper",
            "com.sunwayworld.module.sys.bpmn.bean.CoreBpmnInstanceStatusDTO")),
    GRID_COMPLETETASK(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpAuditableDTO",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpResultDTO",
            "com.sunwayworld.framework.context.concurrent.GikamConcurrentLocker",
            "com.sunwayworld.framework.support.auditable.bean.CoreBpmnParameterDTO",
            "com.sunwayworld.module.sys.bpmn.CoreBpmnHelper",
            "com.sunwayworld.module.sys.bpmn.bean.CoreBpmnInstanceStatusDTO")),
    GRID_REJECTTASK(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpAuditableDTO",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpResultDTO",
            "com.sunwayworld.framework.context.concurrent.GikamConcurrentLocker",
            "com.sunwayworld.framework.support.auditable.bean.CoreBpmnParameterDTO",
            "com.sunwayworld.module.sys.bpmn.CoreBpmnHelper",
            "com.sunwayworld.module.sys.bpmn.bean.CoreBpmnInstanceStatusDTO")),
    GRID_WITHDRAWPROCESS(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpAuditableDTO",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpResultDTO",
            "com.sunwayworld.framework.context.concurrent.GikamConcurrentLocker",
            "com.sunwayworld.framework.support.auditable.bean.CoreBpmnParameterDTO",
            "com.sunwayworld.module.sys.bpmn.CoreBpmnHelper",
            "com.sunwayworld.module.sys.bpmn.bean.CoreBpmnInstanceStatusDTO")),
    TREEGRID_MOVE(Arrays.asList("java.lang.String")),
    FORM_SETID(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map")),
    FORM_SELECT(Arrays.asList("java.lang.String",
            "java.lang.Object",
            "java.util.Map",
            "com.sunwayworld.framework.mybatis.mapper.MapperParameter")),
    FORM_INSERT(Arrays.asList("java.lang.String",
            "java.lang.Object",
            "java.util.Map")),
    FORM_UPDATE(Arrays.asList("java.lang.String",
            "java.lang.Object",
            "java.util.Map",
            "com.sunwayworld.framework.utils.StringUtils",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpResultDTO")),
    FORM_PROCESSTASKSTATUS(Arrays.asList("java.lang.String",
            "java.util.Map",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpAuditableDTO",
            "com.sunwayworld.framework.support.auditable.bean.CoreBpmnParameterDTO")),
    FORM_STARTPROCESS(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpAuditableDTO",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpResultDTO",
            "com.sunwayworld.framework.context.concurrent.GikamConcurrentLocker",
            "com.sunwayworld.framework.support.auditable.bean.CoreBpmnParameterDTO",
            "com.sunwayworld.module.sys.bpmn.CoreBpmnHelper",
            "com.sunwayworld.module.sys.bpmn.bean.CoreBpmnInstanceStatusDTO")),
    FORM_COMPLETETASK(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpAuditableDTO",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpResultDTO",
            "com.sunwayworld.framework.context.concurrent.GikamConcurrentLocker",
            "com.sunwayworld.framework.support.auditable.bean.CoreBpmnParameterDTO",
            "com.sunwayworld.module.sys.bpmn.CoreBpmnHelper",
            "com.sunwayworld.module.sys.bpmn.bean.CoreBpmnInstanceStatusDTO")),
    FORM_REJECTTASK(Arrays.asList("java.lang.String",
            "java.util.List",
            "java.util.Map",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpAuditableDTO",
            "com.sunwayworld.cloud.module.lcdp.base.LcdpResultDTO",
            "com.sunwayworld.framework.context.concurrent.GikamConcurrentLocker",
            "com.sunwayworld.framework.support.auditable.bean.CoreBpmnParameterDTO",
            "com.sunwayworld.module.sys.bpmn.CoreBpmnHelper",
            "com.sunwayworld.module.sys.bpmn.bean.CoreBpmnInstanceStatusDTO"));
    
    private final List<String> importClassNameList;
    
    private LcdpSourceCodeMethodType(List<String> importClassNameList) {
        this.importClassNameList = importClassNameList;
    }

    public List<String> getImportClassNameList() {
        return importClassNameList;
    }
}
